name: health_band_app
description: "A health monitoring app for smart health bands."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.8.0+1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.70.2

  # Notifications
  flutter_local_notifications: ^18.0.1

  # Foreground task (background service)
  flutter_foreground_task: ^8.15.0
  flutter_ringtone_player: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
